# Builds and runs tests in all three supported OSes
# Pushes CI feed if secrets.SLEET_CONNECTION is provided

name: build
on: 
  workflow_dispatch:
    inputs:
      configuration:
        type: choice
        description: Configuration
        options: 
        - Release
        - Debug
  push:
    branches: [ main, dev, 'dev/*', 'feature/*', 'rel/*' ]
    paths-ignore:
      - changelog.md
      - readme.md
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  PackOnBuild: true
  GeneratePackageOnBuild: true
  VersionPrefix: 42.42.${{ github.run_number }}
  VersionLabel: ${{ github.ref }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MSBUILDTERMINALLOGGER: auto
  Configuration: ${{ github.event.inputs.configuration || 'Release' }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: 🙏 build
        run: dotnet build -m:1 -bl:build.binlog

      - name: ⚙ install
        working-directory: bin
        run: dotnet tool update -g dotnet-retest --prerelease --add-source .

      - name: 🧪 test
        run: dotnet retest -- ./src/Sample/

      - name: 🐛 logs
        uses: actions/upload-artifact@v3
        if: runner.debug && always()
        with:
          name: logs
          path: '*.binlog'

      # Only push CI package to sleet feed if building on ubuntu (fastest)
      - name: 🚀 sleet
        env:
          SLEET_CONNECTION: ${{ secrets.SLEET_CONNECTION }}
        if: env.SLEET_CONNECTION != '' && matrix.os == 'ubuntu-latest'
        run: |
          dotnet tool install -g --version 4.0.18 sleet 
          sleet push bin --config none -f --verbose -p "SLEET_FEED_CONTAINER=nuget" -p "SLEET_FEED_CONNECTIONSTRING=${{ secrets.SLEET_CONNECTION }}" -p "SLEET_FEED_TYPE=azure" || echo "No packages found"

  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: ✓ ensure format
        run: |
          dotnet format whitespace --verify-no-changes -v:diag --exclude ~/.nuget
          dotnet format style --verify-no-changes -v:diag --exclude ~/.nuget
